<?php

declare(strict_types=1);

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

namespace Crossmedia\Fourallportal\Command\Event;

use Crossmedia\Fourallportal\Domain\Dto\SyncParameters;
use Crossmedia\Fourallportal\Domain\Repository\EventRepository;
use Crossmedia\Fourallportal\Service\EventExecutionService;
use Psr\Log\LoggerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use TYPO3\CMS\Core\Utility\GeneralUtility;

abstract class AbstractEventCommand extends Command
{
    protected SyncParameters $parameters;
    protected int $maxThreads;

    public function __construct(
        protected EventExecutionService $eventExecutionService,
        protected EventRepository $eventRepository,
        protected LoggerInterface $logger
    ) {
        parent::__construct();
    }

    /**
     * Configure the command by defining the name, options and arguments
     */
    protected function configure()
    {
        $this
            ->addArgument(
                'module',
                InputArgument::OPTIONAL,
                'If passed can be used to only sync one module, using the module or connector name it has in 4AP',
                null
            )
            ->addOption(
                'force',
                'f',
                InputOption::VALUE_NONE,
                'Forces the sync to run regardless of lock and will neither lock nor unlock the task'
            )
            ->addOption(
                'exclude',
                null,
                InputOption::VALUE_REQUIRED,
                'Exclude a list of modules from processing (CSV string module names)',
                null
            )
            ->addOption(
                'max-events',
                null,
                InputOption::VALUE_REQUIRED,
                'Maximum number of events to process. Default is unlimited. Affects only the number of events being executed, if sync is enabled will still sync all',
                0
            )
            ->addOption(
                'max-time',
                null,
                InputOption::VALUE_REQUIRED,
                'Maximum number of seconds that the sync is allowed to run, once expired, will require a new execution to continue',
                0
            )
            ->addOption(
                'max-threads',
                null,
                InputOption::VALUE_REQUIRED,
                'Maximum number of concurrent threads which are allowed to execute events. Ignored if sync=true',
                4
            )
        ;
    }

    /**
     * Configure the sync and execute parameters
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return void
     */
    protected function initialize(InputInterface $input, OutputInterface $output)
    {
        $module = $input->getArgument('module');
        $exclude = (string)$input->getOption('exclude');
        $force = $input->hasOption('force') && $input->getOption('force');
        $maxEvents = (int)$input->getOption('max-events');
        $maxTime = (int)$input->getOption('max-time');
        $this->maxThreads = (int)$input->getOption('max-threads');

        $this->parameters = GeneralUtility::makeInstance(SyncParameters::class)
            ->setModule($module)
            ->setExclude($exclude)
            ->setForce($force)
            ->setEventLimit($maxEvents)
            ->setTimeLimit($maxTime);

        parent::initialize($input, $output); // TODO: Change the autogenerated stub
    }
}
